### ISSUE TITLE
Redesign and refactor HTTP API's static file handling

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi-cloud#20]
The way HTTP API resources handle static files could be improved. Here is a list of issues to be addressed over time.

```
public routeStaticDirectory(
    method: string,
    path: string,
    filePath: string,
    contentType?: string) {
```

- [x] Remove the `method` parameter. Anything other than "GET" doesn't make sense for serving static files. (done in #26)
- [x] Provide a way to upload entire directories, not needing explicit file-by-file declarations.
- [ ] Enable regular expression captures, e.g. "/static/([^/]+)/(.)+" -> "/$1/$2"
- [x] Compare the design with Rest, Heroku, GAE, and other providers. Ensure we have feature parity. (See #4 for reference.)

Related issues:

- [x] Support "folders" in the Lumi layer (https://github.com/pulumi/pulumi-fabric/issues/240)
